FROM node:10
# Create app directory
WORKDIR /home/simple-arb
COPY package*.json ./
RUN npm install
ENV ETHEREUM_RPC_URL=<RPC_URL>
ENV PRIVATE_KEY=<PRIVATE_KEY>
ENV BUNDLE_EXECUTOR_ADDRESS=<BUNDLE_EXECUTOR_ADDRESS>
COPY . .
# CMD ["/bin/sh"]
CMD ["npm","run","start"]
