FROM node:10
# Create app directory
WORKDIR /home/simple-arb
COPY package*.json ./
RUN npm install
ENV ETHEREUM_RPC_URL="https://speedy-nodes-nyc.moralis.io/<MORALIS_KEY>/eth/mainnet"
ENV ETHEREUM_GOERLI_RPC_URL="https://speedy-nodes-nyc.moralis.io/<MORALIS_KEY>/eth/goerli"
ENV PRIVATE_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
ENV BUNDLE_EXECUTOR_ADDRESS="0x0000000000000000000000000000000000000000"
COPY . .
# CMD ["/bin/sh"]
CMD ["npm","run","start"]
